### ISSUE TITLE
go sdk based on turso-cli

### ISSUE THREAD

**Issue by dezren39** [tursodatabase/turso-cli#749] opened 2023-12-16 06:22 UTC
is there a go package i can use as an sdk for the turso data platform? i'm gonna have to go make my own if there isnt but i figure you must have one somewhere inside this repo

**Comment by notrab** [comment] 2023-12-18 12:28
Hey @dezren39 

There's nothing official (aside from what you can see inside the `turso` package [here](https://github.com/tursodatabase/turso-cli/tree/main/internal/turso)).

I started creating something similar for JS which you can see [here](https://github.com/notrab/turso-api).

I'd love to coordinate creating something for Go that has a similar API. Are you [on Discord](https://discord.com/invite/4B5D7hYwub)? Send me a DM (`@notrab`), I'd love to chat more.

**Comment by haaawk** [comment] 2024-05-06 16:06
This is a duplicate of https://github.com/tursodatabase/turso-cli/issues/16

**Closed by haaawk** 2024-05-06 16:06 UTC
