### ISSUE TITLE
Move Turso REST API package to a different repository

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso-cli#581] opened 2023-07-28 10:34 UTC
The Turso REST API package is useful beyond the CLI so let's move it to a `github.com/tursodatabase/go-turso` repository.

**Comment by haaawk** [comment] 2024-05-06 16:25
Duplicate of https://github.com/tursodatabase/turso-cli/issues/16 even author is the same :D

**Closed by haaawk** 2024-05-06 16:25 UTC
Labels: enhancement, good first issue, help wanted
