### ISSUE TITLE
support extensions in `turso dev`

### ISSUE THREAD

**Issue by avinassh** [tursodatabase/turso-cli#808] opened 2024-02-26 17:15 UTC
Right now, people have no way of using extensions when they do `turso dev`. A roundabout way is, running sqld with all the proper configs. well, that sucks.

requested here: https://discord.com/channels/933071162680958986/1211488827156209736/1211488827156209736

**Comment by nkpgardose** [comment] 2024-03-23 07:24
Hi Turso team 👋 

Just to give additional info for this,

```
$ turso db shell http://127.0.0.1:8080
-> select (uuid4());
Error: failed to execute SQL: select (uuid4());
SQL input error: no such function: uuid4 (at offset 8)
```

would be great if extension is available.

**Comment by haaawk** [comment] 2024-05-05 19:14
Duplicate of https://github.com/tursodatabase/turso-cli/issues/636 I believe

**Closed by haaawk** 2024-05-05 19:14 UTC
Labels: developer experience
